-- Trading-booooo v6.8.0-VALIDATED-PARETO-LEARNING
--
-- Raw outcomes still update after every live close, but they are observations rather than
-- production releases. A frozen champion and a frozen alternate are assigned whole scan
-- cycles at normal size. Promotion requires contemporaneous live evidence that net return
-- AND win rate improve while completed-trade supply, slot turnover, capital turnover and
-- notional do not fall. The promoted model is provisional until it repeats that dominance
-- against the old champion as a live control; otherwise it is rolled back.

create table if not exists public.lob_policy_versions (
  version bigint generated by default as identity primary key,
  status text not null check (
    status in (
      'CHAMPION',
      'CHALLENGER',
      'CONTROL',
      'REJECTED',
      'RETIRED',
      'ROLLED_BACK'
    )
  ),
  parent_version bigint references public.lob_policy_versions(version),
  engine_version text not null,
  fingerprint text not null unique,
  source_online_version bigint not null default 0,
  source_pattern_profile_id uuid references public.lob_learning_profiles(id) on delete set null,
  online_profiles jsonb not null default '[]'::jsonb,
  pattern_profile jsonb,
  traffic_fraction numeric not null default 0.5
    check (traffic_fraction >= 0 and traffic_fraction <= 0.5),
  criteria jsonb not null default jsonb_build_object(
    'min_samples_per_arm', 40,
    'early_stop_samples_per_arm', 20,
    'max_samples_per_arm', 120,
    'confidence', 0.90,
    'min_notional_ratio', 0.98,
    'min_common_mix_coverage', 0.80,
    'requires_positive_net_after_costs', true,
    'requires_win_rate_improvement', true,
    'requires_exchange_pattern_mix_adjustment', true,
    'requires_trade_rate_non_decrease', true,
    'requires_capital_turnover_non_decrease', true
  ),
  metrics jsonb not null default '{}'::jsonb,
  decision_reason text,
  evaluation_started_at timestamptz,
  promoted_at timestamptz,
  confirmed_at timestamptz,
  evaluated_at timestamptz,
  retired_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists lob_policy_versions_single_champion_idx
  on public.lob_policy_versions ((1))
  where status = 'CHAMPION';

create unique index if not exists lob_policy_versions_single_alternate_idx
  on public.lob_policy_versions ((1))
  where status in ('CHALLENGER', 'CONTROL');

create index if not exists lob_policy_versions_status_idx
  on public.lob_policy_versions(status, version desc);

alter table public.lob_policy_versions enable row level security;

drop policy if exists lob_policy_versions_service_all on public.lob_policy_versions;
create policy lob_policy_versions_service_all
  on public.lob_policy_versions for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

-- Freeze the exact v6.7 policy that was active at migration time. Historical outcomes are
-- intentionally not a validation cohort: they were generated by several different engines.
insert into public.lob_policy_versions (
  status,
  engine_version,
  fingerprint,
  source_online_version,
  source_pattern_profile_id,
  online_profiles,
  pattern_profile,
  confirmed_at,
  decision_reason
)
select
  'CHAMPION',
  '6.7.0-ONLINE-COIN-LEARNING',
  md5(
    coalesce((
      select jsonb_agg(to_jsonb(p) order by p.exchange, p.market, p.pattern)::text
        from public.lob_market_profiles p
    ), '[]') ||
    coalesce((
      select to_jsonb(lp)::text
        from public.lob_learning_profiles lp
       where lp.active
       order by lp.generated_at desc
       limit 1
    ), 'null')
  ),
  coalesce((
    select sum(p.version)
      from public.lob_market_profiles p
     where p.market = '*'
  ), 0),
  (
    select lp.id
      from public.lob_learning_profiles lp
     where lp.active
     order by lp.generated_at desc
     limit 1
  ),
  coalesce((
    select jsonb_agg(to_jsonb(p) order by p.exchange, p.market, p.pattern)
      from public.lob_market_profiles p
  ), '[]'::jsonb),
  (
    select to_jsonb(lp)
      from public.lob_learning_profiles lp
     where lp.active
     order by lp.generated_at desc
     limit 1
  ),
  now(),
  'INITIAL_V670_POLICY_FROZEN'
where not exists (
  select 1 from public.lob_policy_versions where status = 'CHAMPION'
);

alter table public.lob_online_outcomes
  add column if not exists policy_version bigint references public.lob_policy_versions(version),
  add column if not exists policy_lane text not null default 'LEGACY',
  add column if not exists realized_cost_quote numeric not null default 0,
  add column if not exists capital_seconds numeric not null default 0,
  add column if not exists engine_version text;

alter table public.lob_online_outcomes
  drop constraint if exists lob_online_outcomes_policy_lane_ck,
  drop constraint if exists lob_online_outcomes_realized_cost_ck,
  drop constraint if exists lob_online_outcomes_capital_seconds_ck;

alter table public.lob_online_outcomes
  add constraint lob_online_outcomes_policy_lane_ck
    check (policy_lane in ('CHAMPION', 'CHALLENGER', 'CONTROL', 'LEGACY')) not valid,
  add constraint lob_online_outcomes_realized_cost_ck
    check (realized_cost_quote >= 0) not valid,
  add constraint lob_online_outcomes_capital_seconds_ck
    check (capital_seconds >= 0) not valid;

alter table public.lob_online_outcomes
  validate constraint lob_online_outcomes_policy_lane_ck;
alter table public.lob_online_outcomes
  validate constraint lob_online_outcomes_realized_cost_ck;
alter table public.lob_online_outcomes
  validate constraint lob_online_outcomes_capital_seconds_ck;

create index if not exists lob_online_outcomes_policy_idx
  on public.lob_online_outcomes(policy_version, closed_at desc)
  where policy_version is not null;

-- Existing rows remain LEGACY and cannot vote in a promotion. Monetary fields are filled
-- only for diagnostics and cohort-independent historical analysis.
update public.lob_online_outcomes o
set realized_cost_quote = greatest(0, coalesce(p.realized_cost_quote, 0)),
    capital_seconds = greatest(0, coalesce(p.realized_cost_quote, 0)) *
      greatest(0, o.held_seconds),
    engine_version = p.metadata ->> 'engine_version'
from public.trading_positions p
where p.id = o.position_id
  and o.policy_version is null;

create or replace function public.enrich_lob_online_outcome_policy()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_metadata jsonb;
  v_cost numeric;
  v_version_text text;
  v_version bigint;
  v_lane text;
begin
  select coalesce(p.metadata, '{}'::jsonb), greatest(0, coalesce(p.realized_cost_quote, 0))
    into v_metadata, v_cost
    from public.trading_positions p
   where p.id = new.position_id;

  v_version_text := v_metadata #>> '{lob_signal,policy,version}';
  if coalesce(v_version_text, '') ~ '^[0-9]+$' then
    v_version := v_version_text::bigint;
    if not exists (
      select 1 from public.lob_policy_versions p where p.version = v_version
    ) then
      v_version := null;
    end if;
  end if;
  v_lane := upper(coalesce(
    nullif(v_metadata #>> '{lob_signal,policy,lane}', ''),
    'LEGACY'
  ));
  if v_lane not in ('CHAMPION', 'CHALLENGER', 'CONTROL') then
    v_lane := 'LEGACY';
  end if;

  new.policy_version := v_version;
  new.policy_lane := v_lane;
  new.realized_cost_quote := v_cost;
  new.capital_seconds := v_cost * greatest(0, new.held_seconds);
  new.engine_version := nullif(v_metadata ->> 'engine_version', '');
  return new;
end;
$$;

drop trigger if exists lob_online_outcome_policy_trigger on public.lob_online_outcomes;
create trigger lob_online_outcome_policy_trigger
before insert on public.lob_online_outcomes
for each row execute function public.enrich_lob_online_outcome_policy();

create table if not exists public.lob_policy_cycle_exposures (
  cycle_id uuid primary key references public.trading_cycle_runs(id) on delete cascade,
  scan_id text,
  policy_version bigint not null references public.lob_policy_versions(version),
  policy_lane text not null check (policy_lane in ('CHAMPION', 'CHALLENGER', 'CONTROL')),
  candidate_count integer not null default 0 check (candidate_count >= 0),
  entry_attempts integer not null default 0 check (entry_attempts >= 0),
  reservations integer not null default 0 check (reservations >= 0),
  assigned_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lob_policy_cycle_exposures_version_idx
  on public.lob_policy_cycle_exposures(policy_version, assigned_at desc);

alter table public.lob_policy_cycle_exposures enable row level security;

drop policy if exists lob_policy_cycle_exposures_service_all
  on public.lob_policy_cycle_exposures;
create policy lob_policy_cycle_exposures_service_all
  on public.lob_policy_cycle_exposures for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create or replace function public.create_lob_policy_challenger(
  p_min_new_samples integer default 20
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_champion public.lob_policy_versions%rowtype;
  v_existing public.lob_policy_versions%rowtype;
  v_pattern public.lob_learning_profiles%rowtype;
  v_online jsonb;
  v_source_version bigint;
  v_last_source bigint;
  v_fingerprint text;
  v_created public.lob_policy_versions%rowtype;
begin
  perform pg_advisory_xact_lock(hashtext('lob-policy-governance-v680'));

  select *
    into v_existing
    from public.lob_policy_versions
   where status in ('CHALLENGER', 'CONTROL')
   order by version desc
   limit 1;
  if found then
    return jsonb_build_object(
      'created', false,
      'reason', 'ALTERNATE_ALREADY_ACTIVE',
      'alternate_version', v_existing.version,
      'alternate_status', v_existing.status
    );
  end if;

  select *
    into v_champion
    from public.lob_policy_versions
   where status = 'CHAMPION'
   order by version desc
   limit 1
   for update;
  if not found then
    return jsonb_build_object('created', false, 'reason', 'NO_CHAMPION');
  end if;

  select coalesce(
      jsonb_agg(to_jsonb(p) order by p.exchange, p.market, p.pattern),
      '[]'::jsonb
    ),
    coalesce(sum(p.version) filter (where p.market = '*'), 0)
    into v_online, v_source_version
    from public.lob_market_profiles p;

  select *
    into v_pattern
    from public.lob_learning_profiles
   order by generated_at desc
   limit 1;

  select greatest(
      coalesce(v_champion.source_online_version, 0),
      coalesce(max(source_online_version), 0)
    )
    into v_last_source
    from public.lob_policy_versions;

  if v_source_version - v_last_source < greatest(1, coalesce(p_min_new_samples, 20)) then
    return jsonb_build_object(
      'created', false,
      'reason', 'INSUFFICIENT_NEW_OUTCOMES',
      'source_online_version', v_source_version,
      'required_after_version', v_last_source + greatest(1, coalesce(p_min_new_samples, 20))
    );
  end if;

  v_fingerprint := md5(
    coalesce(v_online::text, '[]') ||
    coalesce(to_jsonb(v_pattern)::text, 'null')
  );
  if exists (
    select 1 from public.lob_policy_versions where fingerprint = v_fingerprint
  ) then
    return jsonb_build_object('created', false, 'reason', 'SNAPSHOT_ALREADY_EVALUATED');
  end if;

  update public.lob_policy_versions
  set evaluation_started_at = now(),
      updated_at = now()
  where version = v_champion.version;

  insert into public.lob_policy_versions (
    status,
    parent_version,
    engine_version,
    fingerprint,
    source_online_version,
    source_pattern_profile_id,
    online_profiles,
    pattern_profile,
    traffic_fraction,
    evaluation_started_at,
    decision_reason
  ) values (
    'CHALLENGER',
    v_champion.version,
    '6.8.0-VALIDATED-PARETO-LEARNING',
    v_fingerprint,
    v_source_version,
    v_pattern.id,
    v_online,
    case when v_pattern.id is null then null else to_jsonb(v_pattern) end,
    0.5,
    now(),
    'COLLECTING_CONTEMPORANEOUS_FULL_SIZE_COHORTS'
  )
  returning * into v_created;

  return jsonb_build_object(
    'created', true,
    'version', v_created.version,
    'parent_version', v_created.parent_version,
    'source_online_version', v_created.source_online_version
  );
end;
$$;

create or replace function public.get_lob_policy_evaluation_dataset()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_champion public.lob_policy_versions%rowtype;
  v_alternate public.lob_policy_versions%rowtype;
  v_phase text;
  v_baseline_version bigint;
  v_candidate_version bigint;
  v_since timestamptz;
  v_baseline_trades jsonb;
  v_candidate_trades jsonb;
  v_baseline_exposures jsonb;
  v_candidate_exposures jsonb;
begin
  select * into v_champion
    from public.lob_policy_versions
   where status = 'CHAMPION'
   order by version desc
   limit 1;
  select * into v_alternate
    from public.lob_policy_versions
   where status in ('CHALLENGER', 'CONTROL')
   order by version desc
   limit 1;

  if v_champion.version is null or v_alternate.version is null then
    return jsonb_build_object('phase', 'IDLE');
  end if;

  if v_alternate.status = 'CHALLENGER' then
    v_phase := 'CHALLENGE';
    v_baseline_version := v_champion.version;
    v_candidate_version := v_alternate.version;
  else
    v_phase := 'CONFIRMATION';
    v_baseline_version := v_alternate.version;
    v_candidate_version := v_champion.version;
  end if;
  v_since := greatest(
    coalesce(v_champion.evaluation_started_at, v_champion.created_at),
    coalesce(v_alternate.evaluation_started_at, v_alternate.created_at)
  );

  select coalesce(jsonb_agg(jsonb_build_object(
      'id', o.position_id,
      'policyVersion', o.policy_version,
      'exchange', o.exchange,
      'market', o.market,
      'pattern', o.pattern,
      'netBps', o.net_bps,
      'profitable', o.profitable,
      'heldSeconds', o.held_seconds,
      'notionalQuote', o.realized_cost_quote,
      'closedAtMs', extract(epoch from o.closed_at) * 1000
    ) order by o.closed_at), '[]'::jsonb)
    into v_baseline_trades
    from public.lob_online_outcomes o
   where o.policy_version = v_baseline_version
     and o.closed_at >= v_since;

  select coalesce(jsonb_agg(jsonb_build_object(
      'id', o.position_id,
      'policyVersion', o.policy_version,
      'exchange', o.exchange,
      'market', o.market,
      'pattern', o.pattern,
      'netBps', o.net_bps,
      'profitable', o.profitable,
      'heldSeconds', o.held_seconds,
      'notionalQuote', o.realized_cost_quote,
      'closedAtMs', extract(epoch from o.closed_at) * 1000
    ) order by o.closed_at), '[]'::jsonb)
    into v_candidate_trades
    from public.lob_online_outcomes o
   where o.policy_version = v_candidate_version
     and o.closed_at >= v_since;

  select coalesce(jsonb_agg(jsonb_build_object(
      'policyVersion', e.policy_version,
      'assignedAtMs', extract(epoch from e.assigned_at) * 1000,
      'candidateCount', e.candidate_count,
      'entryAttempts', e.entry_attempts,
      'reservations', e.reservations
    ) order by e.assigned_at), '[]'::jsonb)
    into v_baseline_exposures
    from public.lob_policy_cycle_exposures e
   where e.policy_version = v_baseline_version
     and e.assigned_at >= v_since;

  select coalesce(jsonb_agg(jsonb_build_object(
      'policyVersion', e.policy_version,
      'assignedAtMs', extract(epoch from e.assigned_at) * 1000,
      'candidateCount', e.candidate_count,
      'entryAttempts', e.entry_attempts,
      'reservations', e.reservations
    ) order by e.assigned_at), '[]'::jsonb)
    into v_candidate_exposures
    from public.lob_policy_cycle_exposures e
   where e.policy_version = v_candidate_version
     and e.assigned_at >= v_since;

  return jsonb_build_object(
    'phase', v_phase,
    'since', v_since,
    'baseline_version', v_baseline_version,
    'candidate_version', v_candidate_version,
    'baseline_trades', v_baseline_trades,
    'candidate_trades', v_candidate_trades,
    'baseline_exposures', v_baseline_exposures,
    'candidate_exposures', v_candidate_exposures
  );
end;
$$;

create or replace function public.apply_lob_policy_decision(
  p_expected_champion bigint,
  p_expected_alternate bigint,
  p_decision text,
  p_metrics jsonb,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_champion public.lob_policy_versions%rowtype;
  v_alternate public.lob_policy_versions%rowtype;
  v_decision text := upper(coalesce(p_decision, ''));
begin
  perform pg_advisory_xact_lock(hashtext('lob-policy-governance-v680'));

  select * into v_champion
    from public.lob_policy_versions
   where status = 'CHAMPION'
   order by version desc
   limit 1
   for update;
  select * into v_alternate
    from public.lob_policy_versions
   where status in ('CHALLENGER', 'CONTROL')
   order by version desc
   limit 1
   for update;

  if v_champion.version is distinct from p_expected_champion or
     v_alternate.version is distinct from p_expected_alternate then
    return jsonb_build_object('applied', false, 'reason', 'STALE_POLICY_STATE');
  end if;

  if v_decision = 'HOLD' then
    update public.lob_policy_versions
    set metrics = coalesce(p_metrics, '{}'::jsonb),
        decision_reason = p_reason,
        evaluated_at = now(),
        updated_at = now()
    where version = v_alternate.version;
  elsif v_decision = 'REJECT' and v_alternate.status = 'CHALLENGER' then
    update public.lob_policy_versions
    set status = 'REJECTED',
        metrics = coalesce(p_metrics, '{}'::jsonb),
        decision_reason = p_reason,
        evaluated_at = now(),
        retired_at = now(),
        updated_at = now()
    where version = v_alternate.version;
    update public.lob_policy_versions
    set evaluation_started_at = null,
        updated_at = now()
    where version = v_champion.version;
  elsif v_decision = 'PROMOTE' and v_alternate.status = 'CHALLENGER' then
    -- The old champion remains alive as a contemporaneous live control. The new champion
    -- is provisional until a second independent cohort confirms the same dominance.
    -- Move the challenger through a transaction-local terminal state first. PostgreSQL
    -- checks partial unique indexes row-by-row, so directly swapping CHALLENGER/CHAMPION
    -- can otherwise collide with the one-alternate/one-champion invariants.
    update public.lob_policy_versions
    set status = 'RETIRED',
        updated_at = now()
    where version = v_alternate.version;
    update public.lob_policy_versions
    set status = 'CONTROL',
        traffic_fraction = 0.5,
        evaluation_started_at = now(),
        metrics = coalesce(p_metrics -> 'baseline', '{}'::jsonb),
        decision_reason = 'LIVE_CONTROL_AFTER_PROVISIONAL_PROMOTION',
        updated_at = now()
    where version = v_champion.version;
    update public.lob_policy_versions
    set status = 'CHAMPION',
        promoted_at = now(),
        confirmed_at = null,
        evaluation_started_at = now(),
        metrics = coalesce(p_metrics -> 'candidate', '{}'::jsonb),
        decision_reason = p_reason,
        evaluated_at = now(),
        updated_at = now()
    where version = v_alternate.version;
  elsif v_decision = 'CONFIRM' and v_alternate.status = 'CONTROL' then
    update public.lob_policy_versions
    set status = 'RETIRED',
        metrics = coalesce(p_metrics -> 'baseline', metrics),
        decision_reason = 'PROVISIONAL_CHAMPION_CONFIRMED',
        evaluated_at = now(),
        retired_at = now(),
        updated_at = now()
    where version = v_alternate.version;
    update public.lob_policy_versions
    set confirmed_at = now(),
        evaluation_started_at = null,
        metrics = coalesce(p_metrics -> 'candidate', metrics),
        decision_reason = p_reason,
        evaluated_at = now(),
        updated_at = now()
    where version = v_champion.version;
  elsif v_decision = 'ROLLBACK' and v_alternate.status = 'CONTROL' then
    update public.lob_policy_versions
    set status = 'ROLLED_BACK',
        metrics = coalesce(p_metrics -> 'candidate', metrics),
        decision_reason = p_reason,
        evaluated_at = now(),
        retired_at = now(),
        updated_at = now()
    where version = v_champion.version;
    update public.lob_policy_versions
    set status = 'CHAMPION',
        confirmed_at = now(),
        evaluation_started_at = null,
        metrics = coalesce(p_metrics -> 'baseline', metrics),
        decision_reason = 'AUTO_ROLLBACK_CONTROL_RESTORED',
        evaluated_at = now(),
        retired_at = null,
        updated_at = now()
    where version = v_alternate.version;
  else
    return jsonb_build_object(
      'applied', false,
      'reason', 'INVALID_DECISION_FOR_PHASE',
      'decision', v_decision,
      'alternate_status', v_alternate.status
    );
  end if;

  return jsonb_build_object(
    'applied', true,
    'decision', v_decision,
    'status', public.get_lob_policy_status()
  );
end;
$$;

create or replace function public.get_lob_policy_status()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with champion as (
    select *
      from public.lob_policy_versions
     where status = 'CHAMPION'
     order by version desc
     limit 1
  ),
  alternate as (
    select *
      from public.lob_policy_versions
     where status in ('CHALLENGER', 'CONTROL')
     order by version desc
     limit 1
  )
  select jsonb_build_object(
    'mode', 'VALIDATED_PARETO_CHAMPION_CHALLENGER',
    'phase', case
      when (select status from alternate) = 'CHALLENGER' then 'CHALLENGE'
      when (select status from alternate) = 'CONTROL' then 'CONFIRMATION'
      else 'IDLE'
    end,
    'champion', (
      select jsonb_build_object(
        'version', version,
        'status', status,
        'parent_version', parent_version,
        'source_online_version', source_online_version,
        'confirmed', confirmed_at is not null,
        'evaluation_started_at', evaluation_started_at,
        'promoted_at', promoted_at,
        'confirmed_at', confirmed_at,
        'metrics', metrics,
        'decision_reason', decision_reason,
        'updated_at', updated_at
      ) from champion
    ),
    'alternate', (
      select jsonb_build_object(
        'version', version,
        'status', status,
        'parent_version', parent_version,
        'source_online_version', source_online_version,
        'traffic_fraction', traffic_fraction,
        'evaluation_started_at', evaluation_started_at,
        'metrics', metrics,
        'decision_reason', decision_reason,
        'updated_at', updated_at
      ) from alternate
    ),
    'raw_outcome_samples', (
      select count(*) from public.lob_online_outcomes
    ),
    'last_raw_update_at', (
      select max(created_at) from public.lob_online_outcomes
    )
  );
$$;

revoke all on function public.enrich_lob_online_outcome_policy() from public;
revoke all on function public.create_lob_policy_challenger(integer) from public;
revoke all on function public.get_lob_policy_evaluation_dataset() from public;
revoke all on function public.apply_lob_policy_decision(bigint, bigint, text, jsonb, text)
  from public;
revoke all on function public.get_lob_policy_status() from public;

grant execute on function public.enrich_lob_online_outcome_policy() to service_role;
grant execute on function public.create_lob_policy_challenger(integer) to service_role;
grant execute on function public.get_lob_policy_evaluation_dataset() to service_role;
grant execute on function public.apply_lob_policy_decision(bigint, bigint, text, jsonb, text)
  to service_role;
grant execute on function public.get_lob_policy_status() to service_role;

-- Capital authority remains untouched: this migration does not write allocation, slot,
-- reserve, size-fraction or loss-limit settings.
