import test from 'node:test';import assert from 'node:assert/strict';
import {advancePortfolio,emptyPortfolio} from '../../../supabase/functions/_shared/self-evolution/portfolio.mjs';
import {comparePortfolios,qualify} from '../../../supabase/functions/_shared/self-evolution/statistics.mjs';
import {readActivePolicy} from '../../../supabase/functions/_shared/self-evolution/runtime.mjs';
const capital={capital_usdt:332,margin_usdt:150,leverage:3,max_slots:10,taker_fee:.0005,latency_ms:100,ioc_max_bps:12};
const start=Date.parse('2026-09-20T00:00:00Z');
const q=(at,bid)=>({at_ms:at,received_at_ms:at,bid,ask:bid+.01,buy_vwap:bid+.02,sell_vwap:bid-.02,bid_depth_usdt:10000,ask_depth_usdt:10000,coverage:true});
function state(){const s=emptyPortfolio(capital,start);s.cash-=150;s.filled=1;s.positions.XUSDT={id:'position-1',symbol:'XUSDT',entry_at:new Date(start).toISOString(),entry_at_ms:start,entry_price:100,original_quantity:4.5,remaining_quantity:4.5,entry_fee:.225,entry_notional:450,margin:150,hard_stop_price:97.5,peak_price:110,last_high_at:start,last_observation:start,p142_at:start,filters:{priceTick:.01,quantityStep:.01,minNotionalUsdt:5,minQuantity:.01},branch:'V30_SCORE',regime:'STRONG_TREND',metadata:{exitAuthority:{version:'AI_EXIT_AUTHORITY_2',generation:'position-1:'+new Date(start).toISOString(),initialFloor:97.5,hardFloor:98.8,softLevel:105,softReason:'retestAnchor_LOCK'}},decision_id:'entry'};return s;}
const event=(at,bid)=>({id:'e'+at,symbol:'XUSDT',at_ms:at,received_at_ms:at,quote:q(at,bid)});
function dependencies(decision,bid=104){return {capital,decide:async()=>({valid:true,authority:'GPT_FINAL_ONLY',decision,latency_ms:1,refresh_error:null}),fillQuote:async(_s,at)=>q(at,bid),candles:async()=>[],funding:async()=>0,capture:async()=>({status:'UNAVAILABLE'})};}
for(const action of ['HOLD','PROTECT','EXIT'])test('portfolio soft candidate obeys only FINAL '+action,async()=>{let s=state();const d=dependencies(action);s=await advancePortfolio(s,event(start+5000,104),d);assert.equal(s.trades.length,0);s=await advancePortfolio(s,event(start+10000,104),d);assert.equal(s.trades.length,0,'future fill cannot settle early');s=await advancePortfolio(s,event(start+10100,104),d);assert.equal(s.trades.length,action==='EXIT'?1:0);if(action!=='EXIT'){assert.ok(s.positions.XUSDT.hard_stop_price>=98.8);assert.equal(s.positions.XUSDT.remaining_quantity,4.5);}if(action==='PROTECT')assert.equal(s.positions.XUSDT.metadata.fd1Hold.protection.exposureIncrease,false);});
test('hard stop during pending arbitration closes without waiting',async()=>{let s=state(),calls=0,d={...dependencies('HOLD',97),decide:async()=>{calls++;return {valid:true,authority:'GPT_FINAL_ONLY',decision:'HOLD',latency_ms:20000};}};s=await advancePortfolio(s,event(start+5000,104),d);s=await advancePortfolio(s,event(start+10000,97),d);assert.equal(calls,1);assert.equal(s.trades.length,0);assert.equal(s.pending_fills[0].kind,'EXIT');const cash=s.cash;s=await advancePortfolio(s,event(start+10050,97),d);assert.equal(s.cash,cash,'pending exit cannot release capital');s=await advancePortfolio(s,event(start+10100,97),d);assert.equal(s.trades.length,1);assert.equal(s.trades[0].exit_authority,'HARD_SAFETY');assert.ok(s.trades[0].fees_usdt>0);assert.equal(Object.keys(s.positions).length,0);await assert.rejects(()=>advancePortfolio(s,event(start+10100,97),d),/CAUSAL/);});
test('provider failure cannot close soft position and missing exit fill cannot become a winner',async()=>{let s=state(),d={...dependencies('EXIT'),decide:async()=>({valid:false,error:'TIMEOUT',latency_ms:1})};s=await advancePortfolio(s,event(start+5000,104),d);s=await advancePortfolio(s,event(start+10000,104),d);assert.equal(s.trades.length,0);assert.ok(s.positions.XUSDT.metadata.fd1Hold.retryAfter);s=await advancePortfolio(s,event(start+15000,97),{...d,fillQuote:async()=>null});assert.equal(s.trades.length,0);assert.ok(s.missing.some(x=>x.reason==='EXIT_FILL_UNRESOLVED'));});
test('frozen sizing cannot be changed by research',async()=>{await assert.rejects(()=>advancePortfolio(state(),event(start+5000,104),{...dependencies('HOLD'),capital:{...capital,margin_usdt:300}}),/CAPITAL_MANIFEST_DRIFT/);});
test('comparison includes flat days and rejects concentration / immature holdout',()=>{const trade=(day,id,net)=>({closed_ms:start+day*86400000,entry_decision_id:id,net_usdt:net,symbol:'XUSDT',regime:'BREAKOUT'}),b={trades:[trade(1,'one',1),trade(2,'two',-1)]},n={trades:[trade(1,'one',2),trade(2,'two',-.5)]};const c=comparePortfolios(b,n,{start,end:start+5*86400000});assert.equal(c.pairs.length,6);assert.equal(c.max_symbol_profit_share,1);assert.equal(c.winner_retention_ratio,1);assert.ok(qualify({}).reasons.includes('HOLDOUT_NOT_MATURE'));});
test('policy outage bounded and returns immutable builtin',async()=>{const begun=Date.now(),r=await readActivePolicy({env:k=>k==='SUPABASE_URL'?'https://test':'test',fetchFn:()=>new Promise(()=>{}),timeoutMs:10});assert.ok(Date.now()-begun<250);assert.equal(r.bundle.policy_version,'POLICY_BASELINE_V105');assert.equal(r.bundle.stages.ENTRY.gpt_rubric.length,0);});
