// Generated by research/v10_continuation/run_v10_lane_exit_r1.py only after all
// three regime-specific exit lanes pass immutable gates.  Empty means fail closed.
export const V10_LANE_EXIT_REVISION = "V10-LANES-EXIT-R1-UNSELECTED" as const;
export const V10_LANE_EXIT_SPEC_SHA256 = "UNSELECTED" as const;
export const V10_LANE_EXIT_POLICY = {} as const;
export type V10LaneExitPolicy = typeof V10_LANE_EXIT_POLICY;
