import test from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir} from 'node:fs/promises';import {pathToFileURL} from 'node:url';
async function fixture(t){const {PGlite}=await import(pathToFileURL(process.env.PGLITE_MODULE).href),db=new PGlite();t.after(()=>db.close());
 await db.exec(`create table leader20_clock_slots(slot_at timestamptz primary key,batch_id uuid,slot_status text,capture_ready_count int,order_sent_at timestamptz,decision_deadline timestamptz,batch_reason text,updated_at timestamptz);
 create table gpt_final_entry_reviews(record jsonb,purpose text,decision text,api_completed_at timestamptz,completed_at timestamptz);
 create index leader20_clock_gpt_batch on gpt_final_entry_reviews((record#>>'{packet,leader20,batch_id}')) where purpose='PRODUCTION';
 create table expire_test_calls(n int);insert into expire_test_calls values(0);
 create function leader20_clock_execution_expire() returns void language sql as 'update public.expire_test_calls set n=n+1';`);
 const dir=new URL('../supabase/migrations/',import.meta.url),files=(await readdir(dir)).filter(x=>x.endsWith('_bounded_clock_completion_maintenance.sql'));assert.equal(files.length,1);await db.exec(await readFile(new URL(files[0],dir),'utf8'));
 const add=async({expired=false,capture=1,status='AI_REVIEWING',offset=0}={})=>{const batch=crypto.randomUUID();await db.query(`insert into leader20_clock_slots values(clock_timestamp()+($1||' seconds')::interval,$2,$3,$4,null,clock_timestamp()+($5||' seconds')::interval,null,'2026-01-01',null,null,null)`,[offset,batch,status,capture,expired?-50:500]);return batch;};
 const review=async(batch,{symbol='BTCUSDT',decision='BUY',purpose='PRODUCTION',task='ENTRY',kind='FD1_ENTRY',late=false}={})=>db.query(`insert into gpt_final_entry_reviews values($1,$2,$3,clock_timestamp()+($4||' seconds')::interval,clock_timestamp())`,[{kind,packet:{symbol,task,leader20:{batch_id:batch}}},purpose,decision,late?600:-100]);
 const row=async b=>(await db.query('select * from leader20_clock_slots where batch_id=$1',[b])).rows[0];return {db,add,review,row,run:()=>db.query('select leader20_clock_telemetry_maintain()')};}
test('completed live BUY gets the same DECIDED status and immutable deadline',async t=>{const f=await fixture(t),b=await f.add();await f.review(b);const before=await f.row(b);await f.run();const after=await f.row(b);assert.equal(after.slot_status,'DECIDED');assert.equal(+after.decision_deadline,+before.decision_deadline);assert.equal(after.completion_reconciled_batch_id,b);});
test('completed expired BUY is reconciled once without churning timestamp or replaying authority',async t=>{const f=await fixture(t),b=await f.add({expired:true,status:'EXPIRED'});await f.review(b);await f.run();const before=await f.row(b);await f.run();const after=await f.row(b);assert.equal(after.slot_status,'EXPIRED');assert.equal(+after.updated_at,+before.updated_at);assert.equal(+after.completion_telemetry_checked_at,+before.completion_telemetry_checked_at);});
test('zero-BUY completed slot becomes DONE, while late completion cannot revive BUY',async t=>{const f=await fixture(t),a=await f.add(),b=await f.add({expired:true,offset:1});await f.review(a,{decision:'SKIP'});await f.review(b,{late:true});await f.run();assert.equal((await f.row(a)).slot_status,'DONE');assert.equal((await f.row(b)).slot_status,'EXPIRED');assert.equal((await f.row(b)).completion_reconciled_batch_id,b);});
test('distinct symbol counting preserves multi-candidate completion semantics',async t=>{const f=await fixture(t),b=await f.add({capture:2});await f.review(b);await f.review(b);await f.run();assert.equal((await f.row(b)).slot_status,'AI_REVIEWING');assert.equal((await f.row(b)).completion_reconciled_at,null);await f.review(b,{symbol:'ETHUSDT'});await f.run();assert.equal((await f.row(b)).slot_status,'DECIDED');});
test('test, replay, HOLD and wrong-kind documents cannot complete a production entry slot',async t=>{const f=await fixture(t),b=await f.add();for(const opts of [{purpose:'DRYRUN'},{purpose:'REPLAY'},{task:'HOLD'},{kind:'FD1_HOLD'}])await f.review(b,opts);await f.run();assert.equal((await f.row(b)).completion_reconciled_at,null);});
test('one call checks at most 32 slots and durable cursor gives unchecked history its next turn',async t=>{const f=await fixture(t);for(let i=0;i<50;i++)await f.add({expired:true,status:'EXPIRED',offset:i});await f.run();assert.equal((await f.db.query('select count(*)::int n from leader20_clock_slots where completion_telemetry_checked_at is not null')).rows[0].n,32);await f.run();assert.equal((await f.db.query('select count(*)::int n from leader20_clock_slots where completion_telemetry_checked_at is not null')).rows[0].n,50);});
test('new live slots precede expired history and no old BUY is submitted',async t=>{const f=await fixture(t);for(let i=0;i<40;i++)await f.add({expired:true,status:'EXPIRED',offset:i});const b=await f.add({offset:41});await f.review(b);await f.run();assert.equal((await f.row(b)).slot_status,'DECIDED');assert.equal((await f.db.query('select n from expire_test_calls')).rows[0].n,1);});
test('a changed batch identity is eligible again without inheriting previous completion',async t=>{const f=await fixture(t),b=await f.add({expired:true,status:'EXPIRED'});await f.review(b);await f.run();const replacement=crypto.randomUUID();await f.db.query('update leader20_clock_slots set batch_id=$1 where batch_id=$2',[replacement,b]);await f.run();assert.equal((await f.row(replacement)).completion_reconciled_batch_id,b);assert.equal((await f.row(replacement)).slot_status,'EXPIRED');});
