import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {pathToFileURL} from 'node:url';
const load=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
async function fixture(t){const {PGlite}=await import(pathToFileURL(process.env.PGLITE_MODULE).href),db=new PGlite();t.after(()=>db.close());
 const v18=load('supabase/migrations/20260911000759_v18_ops_isolation.sql'),v19=load('supabase/migrations/20260912104847_v19_scope_aware_entry_control.sql');
 await db.exec(`create table v11_long_regime_runtime(singleton boolean,circuit_open boolean,circuit_reason text,last_error text,incident_id uuid,incident_generation bigint,incident_kind text,incident_opened_at timestamptz,incident_last_checked_at timestamptz,incident_resolved_at timestamptz,updated_at timestamptz,live_enabled boolean);
 create table v17_operator_control(singleton boolean,entry_enabled boolean,legacy_entries_retired boolean);insert into v17_operator_control values(true,true,true);
 create table trading_settings(id int,mode text,pause_new_entries boolean,scalp_kill_switch boolean,withdrawal_mode boolean,manual_intervention_required boolean,emergency_liquidation boolean,pause_lock_reason text);insert into trading_settings values(1,'LIVE_LIMITED',false,false,false,false,false,null);
 create table v11_long_regime_positions(state text);create table v11_long_regime_orders(state text,response_payload jsonb);
 create function v17_acquire_execution_lease(uuid) returns boolean language sql as 'select true';create function v17_release_execution_lease(uuid) returns void language sql as 'select null::void';create function v18_require_lease(uuid) returns void language sql as 'select null::void';`);
 await db.exec(v18.slice(v18.indexOf('create table if not exists public.v18_ops_incidents'),v18.indexOf('alter table public.v18_ops_incidents enable')));
 await db.exec(v19.slice(v19.indexOf('alter table public.v18_ops_incidents'),v19.indexOf('alter table public.v11_long_regime_runtime')));
 for(const [source,name] of [[v18,'v18_record_incident'],[v19,'v19_record_incident']]){const at=source.indexOf('create or replace function public.'+name);await db.exec(source.slice(at,source.indexOf('end $$;',at)+7));}
 await db.exec(`insert into v11_long_regime_runtime(singleton,circuit_open,circuit_reason,last_error,incident_id,incident_generation,incident_kind,updated_at,live_enabled) values(true,true,'ACCOUNT_ENTRY_HOLD:ACCOUNT_EVIDENCE_INCOMPLETE_OR_STALE',null,'4e0deb37-e159-4521-ad90-916f58fc1cc6',145,'MANUAL_REVIEW_REQUIRED',now(),true);
 insert into v18_ops_incidents(id,generation,kind,reason,evidence) values('3d38253a-77a8-4b6b-ae78-6b38d41987a1',144,'INCOMPLETE_OR_STALE_SNAPSHOT','ACCOUNT_ENTRY_HOLD:ACCOUNT_EVIDENCE_INCOMPLETE_OR_STALE','{"decision":{"reasons":["ACCOUNT_EVIDENCE_INCOMPLETE_OR_STALE"]}}'),('4e0deb37-e159-4521-ad90-916f58fc1cc6',145,'MANUAL_REVIEW_REQUIRED','ACCOUNT_ENTRY_HOLD:ACCOUNT_EVIDENCE_INCOMPLETE_OR_STALE','{"source":"PRE_EXISTING_WRITER"}');`);
 const a={expectedIncident:'4e0deb37-e159-4521-ad90-916f58fc1cc6',previousIncident:'3d38253a-77a8-4b6b-ae78-6b38d41987a1',version:'REVIEW_SNAPSHOT_EPOCH_145_1',commit:'a'.repeat(40),owner:crypto.randomUUID(),postmaster:'2026-10-02T10:31:45Z',evidence:{portfolio:{exchange:'binance_futures',account_scope:'futures',positions_complete:true,positions:[],observation:{source:'BINANCE_ACCOUNT_REST',id:crypto.randomUUID(),requested_at_ms:Date.now(),received_at_ms:Date.now()}},openOrders:{complete:true,orders:[],algos:[],observed_at_ms:Date.now()}}};
 await db.exec("create role anon;create role authenticated;create role service_role;");
 await db.exec(load('supabase/migrations/20261002123500_exact_snapshot_review_rpc.sql').replaceAll('pg_postmaster_start_time()',"timestamptz '2026-10-02T10:31:45Z'"));
 const apply=()=>db.query('select public.trading_review_snapshot_epoch145($1::jsonb)',[a]);
 return {db,a,apply};
}
test('review retains circuit and actual incident RPC creates new epoch requiring normal recovery',async t=>{const f=await fixture(t);await f.apply();const r=(await f.db.query('select * from v11_long_regime_runtime')).rows[0];assert.equal(r.circuit_open,true);assert.equal(r.incident_generation,146);assert.equal(r.incident_kind,'INCOMPLETE_OR_STALE_SNAPSHOT');assert.equal((await f.db.query('select clean_checks from v18_ops_incidents where generation=146')).rows[0].clean_checks,0);assert.equal((await f.db.query("select count(*)::int n from v18_ops_incidents where status='SUPERSEDED'")).rows[0].n,2);});
test('changed incident refuses operator reclassification',async t=>{const f=await fixture(t);await f.db.exec('update v11_long_regime_runtime set incident_generation=146');await assert.rejects(f.apply,/REVIEW_EXACT_INCIDENT_CAS_MISS/);});
test('stale or incomplete account evidence refuses review without circuit reset',async t=>{const f=await fixture(t);f.a.evidence.portfolio.observation.requested_at_ms-=4000;await assert.rejects(f.apply,/REVIEW_FRESH_FLAT_EVIDENCE_MISSING/);assert.equal((await f.db.query('select circuit_open from v11_long_regime_runtime')).rows[0].circuit_open,true);});
test('UNKNOWN order blocks review even with flat venue reads',async t=>{const f=await fixture(t);await f.db.exec("insert into v11_long_regime_orders values('UNKNOWN','{}')");await assert.rejects(f.apply,/REVIEW_EXPOSURE_CHANGED/);});
test('operator halt and postmaster changes cannot be bypassed',async t=>{const f=await fixture(t);await f.db.exec('update trading_settings set pause_new_entries=true');await assert.rejects(f.apply,/REVIEW_OPERATOR_HALT/);f.a.postmaster='2026-10-02T10:32:45Z';await assert.rejects(f.apply,/REVIEW_VERSION_OR_RESTART/);});

test('review cannot be rerun and anon/authenticated cannot invoke the exact RPC',async t=>{const f=await fixture(t);await f.apply();await assert.rejects(f.apply,/REVIEW_EXACT_INCIDENT_CAS_MISS/);const r=(await f.db.query("select has_function_privilege('anon','public.trading_review_snapshot_epoch145(jsonb)','EXECUTE') anon,has_function_privilege('authenticated','public.trading_review_snapshot_epoch145(jsonb)','EXECUTE') authenticated,has_function_privilege('service_role','public.trading_review_snapshot_epoch145(jsonb)','EXECUTE') service_role")).rows[0];assert.equal(r.anon,false);assert.equal(r.authenticated,false);assert.equal(r.service_role,true);});
test('missing reviewed release commit is refused',async t=>{const f=await fixture(t);delete f.a.commit;await assert.rejects(f.apply,/REVIEW_VERSION_OR_RESTART/);});
