import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
const modulePath=process.env.PGLITE_MODULE || 'C:/Users/lkr99/Documents/Codex/2026-09-25/sanbital-trading-booooo-production-execution-deepseek/.audit/node_modules/@electric-sql/pglite/dist/index.js';
const {PGlite}=await import(pathToFileURL(modulePath).href);
test('private RPC: authorization, leases, caps, idempotency and no trading mutation',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
 create table public.v11_long_regime_signals(id uuid, symbol text,created_at timestamptz,status text,features jsonb);
 create table public.v11_long_regime_positions(id uuid,signal_id uuid,symbol text,entry_at timestamptz,entry_price numeric,state text,metadata jsonb);
 create table public.v17_market_scan_runs(captured_at timestamptz,details jsonb);
 grant select on public.v11_long_regime_signals,public.v11_long_regime_positions,public.v17_market_scan_runs to service_role;`);
 await db.exec(await readFile(new URL('../../supabase/migrations/20260925131209_doa_capture_live.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../../supabase/migrations/20260925135156_doa_gpt_capture_context.sql',import.meta.url),'utf8'));
 const rpc=async(action,body={})=>(await db.query('select public.doa_capture_rpc($1,$2::jsonb) as r',[action,JSON.stringify({worker_id:'worker-test-123',...body})])).rows[0].r;
 await db.exec(`insert into doa_capture.control(id,enabled,protocol_sha256,starts_at,ends_at) values(1,false,repeat('a',64),now()-interval '1 minute',now()+interval '1 day');set role service_role;`);
 assert.equal((await rpc('watch')).enabled,false);
 await db.exec('reset role;set role anon;');
 await assert.rejects(rpc('status'),/permission denied/);
 await assert.rejects(db.query('select * from doa_capture.control'),/permission denied/);
 await db.exec(`reset role;update doa_capture.control set enabled=true;insert into public.v11_long_regime_signals values('00000000-0000-0000-0000-000000000001','BTCUSDT',now(),'REJECTED','{"strategy":"LEADER_MOMENTUM_V17"}');set role service_role;`);
 assert.equal((await rpc('watch')).enabled,true);
 const context=async()=> (await db.query("select public.doa_gpt_capture_context('BTCUSDT',now()) as c")).rows[0].c;
 assert.equal((await context()).reason,'DISABLED');
 await db.exec(`reset role;update doa_capture.control set gpt_context_enabled=true,heartbeat_at=now(),metrics='{"live_contexts":{"BTCUSDT":{"status":"AVAILABLE","sentinel":1}}}';set role service_role;`);
 assert.equal((await context()).sentinel,1);
 await db.exec(`reset role;update doa_capture.control set heartbeat_at=now()-interval '30 seconds';set role service_role;`);
 assert.equal((await context()).reason,'STALE_OR_FUTURE');
 await db.exec(`reset role;update doa_capture.control set heartbeat_at=now()+interval '30 seconds';set role service_role;`);
 assert.equal((await context()).reason,'STALE_OR_FUTURE');
 await db.exec('reset role;set role anon;');
 await assert.rejects(context(),/permission denied/);
 await db.exec('reset role;set role service_role;');
 assert.equal((await rpc('watch',{worker_id:'other-worker-123'})).reason,'LEASE_BUSY');
 const batch={batch_id:'00000000-0000-0000-0000-000000000002',rows:[{kind:'micro',symbol:'BTCUSDT',at:new Date().toISOString(),payload:{book_complete:false}}]};
 assert.equal((await rpc('ingest',batch)).inserted,1);
 const first=(await rpc('status')).bytes_reserved;
 assert.equal((await rpc('ingest',batch)).duplicate,true);
 assert.equal((await rpc('status')).bytes_reserved,first);
 assert.equal((await db.query('select count(*) n from doa_capture.candidates')).rows[0].n,1);
 await assert.rejects(db.query("update public.v11_long_regime_signals set status='FILLED'"),/permission denied/);
 await assert.rejects(rpc('ingest',{...batch,batch_id:'00000000-0000-0000-0000-000000000003',rows:[{...batch.rows[0],at:'2099-01-01'}]}),/timestamp bounds/);
 await db.exec('reset role;update doa_capture.control set bytes_reserved=500000000;set role service_role;');
 assert.equal((await rpc('ingest',batch)).reason,'CAP_REACHED');
 assert.equal((await rpc('watch')).enabled,false);
 await db.close();
});
