// Read-only, deterministic DEV analysis. No network, policy writes or fitted trading gate.
import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
const read=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url)));
const d=read('snapshot.json'), historicalSource=read('historical.json');
const supplement=read('supplement.json');
const keys=['spread_bps','ask_depth_25bps_usdt','bid_depth_25bps_usdt','ask_depth_to_order','bid_depth_to_order','book_imbalance_25bps','est_buy_slippage_bps','max_ask_wall_to_order','max_bid_wall_to_order','taker_buy_ratio_5m','taker_buy_ratio_15m','taker_buy_ratio_60m','buyer_share_change','oi_change_5m','oi_change_60m','funding_rate','premium_index','quote_volume_5m_usdt'];
const num=x=>x===null||x===undefined||x===''?null:Number.isFinite(+x)?+x:null;
const sum=(a,f=x=>x)=>a.reduce((s,x)=>s+f(x),0),mean=a=>a.length?sum(a)/a.length:null;
const quant=(a,p)=>{a=a.filter(x=>x!==null&&Number.isFinite(x)).sort((a,b)=>a-b);if(!a.length)return null;const v=(a.length-1)*p,i=Math.floor(v);return a[i]+(a[Math.min(i+1,a.length-1)]-a[i])*(v-i);};
const stats=a=>{a=a.filter(x=>x!==null&&Number.isFinite(x));return{n:a.length,mean:mean(a),p10:quant(a,.1),p50:quant(a,.5),p90:quant(a,.9),p95:quant(a,.95),min:a.length?Math.min(...a):null,max:a.length?Math.max(...a):null};};
function rng(seed=20260925){let s=seed;return()=>((s=(Math.imul(1664525,s)+1013904223)>>>0)/4294967296);}
const doa=r=>num(r.mfe_60)===null||num(r.mae_60)===null?null:+(+r.mfe_60<.005&&+r.mae_60<=-.012);
const early=r=>num(r.mfe_5)===null?null:+(+r.mfe_5<.003);
const stop=r=>num(r.mae_60)===null?null:+(+r.mae_60<=-.012);
const stop25=r=>num(r.mae_60)===null?null:+(+r.mae_60<=-.025);
const peak=r=>num(r.peak_price)===null||!(+r.entry_price>0)?null:+(+r.peak_price/+r.entry_price-1<.003);
const historical=historicalSource.map(r=>({...r,...Object.fromEntries(['entry_price','peak_price'].map(k=>[k,d.candidates.find(x=>x.signal_id===r.signal_id)?.[k]]))}));
assert.equal(historical.length,68);assert.equal(new Set(historical.map(x=>x.signal_id)).size,68);
function fullPermutation(rows,k){const a=rows.map(r=>({x:num(r.facts?.[k]),y:doa(r),id:r.signal_id})).filter(r=>r.x!==null&&r.y!==null).sort((a,b)=>a.x-b.x||a.id.localeCompare(b.id));const n=Math.floor(a.length/3),ys=a.map(r=>r.y),diff=p=>sum(p.slice(-n))/n-sum(p.slice(0,n))/n,observed=diff(ys),rand=rng();let extreme=0;for(let r=0;r<10000;r++){const p=ys.slice();for(let i=p.length-1;i>0;i--){const j=Math.floor(rand()*(i+1));[p[i],p[j]]=[p[j],p[i]];}if(Math.abs(diff(p))>=Math.abs(observed)-1e-12)extreme++;}return{key:k,n:a.length,tailN:n,eventsLow:sum(ys.slice(0,n)),eventsHigh:sum(ys.slice(-n)),delta:observed,p:(extreme+1)/10001,bonferroni:Math.min(1,18*(extreme+1)/10001)};}
function thin(a,ms){const last=new Map();return a.slice().sort((a,b)=>Date.parse(a.candidate_at)-Date.parse(b.candidate_at)||a.signal_id.localeCompare(b.signal_id)).filter(x=>{const t=Date.parse(x.candidate_at),p=last.get(x.symbol);if(p===undefined||t-p>=ms){last.set(x.symbol,t);return true;}return false;});}
function tertiles(rows,k,label,ties=false){const a=rows.map(r=>({...r,x:num(r.facts?.[k]),y:label(r)})).filter(r=>r.x!==null&&r.y!==null).sort((a,b)=>a.x-b.x||a.signal_id.localeCompare(b.signal_id));const n=a.length;if(n<6)return[];const lo=quant(a.map(r=>r.x),1/3),hi=quant(a.map(r=>r.x),2/3);if(ties&&lo===hi)return[];const size=Math.floor(n/3),extra=n%3,first=size+(extra>0?1:0),last=size;return a.map((r,i)=>({...r,g:ties?(r.x<=lo?0:r.x>=hi?1:null):(i<first?0:i>=n-last?1:null)})).filter(r=>r.g!==null);}
function compare(a,rounds=10000){const n0=a.filter(x=>x.g===0).length,n1=a.length-n0;if(!n0||!n1)return null;const s0=sum(a.filter(x=>!x.g),x=>x.y),s1=sum(a.filter(x=>x.g),x=>x.y),delta=s1/n1-s0/n0,rand=rng();let extreme=0;const ys=a.map(x=>x.y);for(let r=0;r<rounds;r++){const p=ys.slice();for(let i=p.length-1;i>0;i--){const j=Math.floor(rand()*(i+1));[p[i],p[j]]=[p[j],p[i]];}const s=sum(p.slice(0,n0));if(Math.abs((s0+s1-s)/n1-s/n0)>=Math.abs(delta)-1e-12)extreme++;}return{n0,n1,events0:s0,events1:s1,rateLow:s0/n0,rateHigh:s1/n1,delta,p:(extreme+1)/(rounds+1)};}
function clusterCI(a,groupBy,rounds=2000){const groups=Object.values(Object.groupBy(a,groupBy)).map(g=>({n0:g.filter(x=>!x.g).length,n1:g.filter(x=>x.g).length,s0:sum(g.filter(x=>!x.g),x=>x.y),s1:sum(g.filter(x=>x.g),x=>x.y)}));if(groups.length<2)return{clusters:groups.length,ci:null};const rand=rng(20260926),ds=[];for(let r=0;r<rounds;r++){let n0=0,n1=0,s0=0,s1=0;for(let i=0;i<groups.length;i++){const g=groups[Math.floor(rand()*groups.length)];n0+=g.n0;n1+=g.n1;s0+=g.s0;s1+=g.s1;}if(n0&&n1)ds.push(s1/n1-s0/n0);}return{clusters:groups.length,validDraws:ds.length,ci:[quant(ds,.025),quant(ds,.975)]};}
function tests(rows,label,ties=false,cluster=false){const out=keys.map(k=>{const a=tertiles(rows,k,label,ties);return{key:k,...compare(a),...(cluster&&a.length?{symbolDay:clusterCI(a,x=>x.symbol+':'+new Date(x.candidate_at).toISOString().slice(0,10)),utcDay:clusterCI(a,x=>new Date(x.candidate_at).toISOString().slice(0,10))}:{})};});const valid=out.filter(x=>x.p!==undefined).sort((a,b)=>a.p-b.p);let prev=0;for(let i=0;i<valid.length;i++){prev=Math.max(prev,Math.min(1,valid[i].p*(valid.length-i)));valid[i].holm=prev;}return out;}
const expanded=d.candidates.filter(x=>x.facts),filled=expanded.filter(x=>x.position_id),pre=d.candidates.filter(x=>x.pre?.book).map(x=>({...x,facts:x.pre.book}));
const cohorts={replayBUY68:historical,allStoredInitial:expanded,liveInitialBUY:expanded.filter(x=>x.initial_gpt_decision==='BUY'),allPreDispatch:pre};
const result={metadata:{captured_at:d.captured_at,seed:20260925,permutations:10000,bootstrap:2000,scope:'DEV_ONLY',sha256:crypto.createHash('sha256').update(fs.readFileSync(new URL('snapshot.json',import.meta.url))).digest('hex')},claim1:{}};
result.reviewerStyleFullPermutation=keys.map(k=>fullPermutation(historical,k));
for(const[name,rows]of Object.entries(cohorts))result.claim1[name]={rows:rows.length,symbols:new Set(rows.map(x=>x.symbol)).size,labelled:rows.filter(x=>doa(x)!==null).length,doa:sum(rows,x=>doa(x)??0),tests:tests(rows,doa,false,name==='replayBUY68'),tiePreserving:tests(rows,doa,true),definitions:{mfe5Below03:{events:sum(rows,x=>early(x)??0),tests:tests(rows,early)},stop12:{events:sum(rows,x=>stop(x)??0),tests:tests(rows,stop)},stop25:{events:sum(rows,x=>stop25(x)??0),tests:tests(rows,stop25)}},thinned60:{n:thin(rows,3600000).length,tests:tests(thin(rows,3600000),doa)},thinned180:{n:thin(rows,10800000).length,tests:tests(thin(rows,10800000),doa)},firstSymbol:{n:thin(rows,Infinity).length,tests:tests(thin(rows,Infinity),doa)}};
result.claim1.actualPeak={n:filled.length,events:sum(filled,x=>peak(x)??0),tests:tests(filled,peak)};
const legacy=d.positions.filter(x=>num(x.legacy_spread)!==null).map(x=>({...x,candidate_at:x.entry_at,facts:{spread_bps:num(x.legacy_spread),book_imbalance_25bps:num(x.legacy_imbalance)}}));
result.claim1.legacyOtherStrategy={n:legacy.length,range:[legacy[0]?.entry_at,legacy.at(-1)?.entry_at],strategyCounts:Object.fromEntries(Object.entries(Object.groupBy(legacy,x=>x.strategy??'legacy_unspecified')).map(([k,a])=>[k,a.length])),tests:tests(legacy,peak)};
const orderRows=supplement.orderFeatures.filter(x=>num(x.spread)!==null).map(x=>({...x,candidate_at:x.candidate_at??x.created_at,facts:{spread_bps:num(x.spread),est_buy_slippage_bps:num(x.slippage)}}));
result.claim1.allOrderSnapshots={n:orderRows.length,labelled:orderRows.filter(x=>doa(x)!==null).length,doa:sum(orderRows,x=>doa(x)??0),tests:tests(orderRows,doa),actualPeak:tests(orderRows,peak),byPatch:Object.fromEntries(Object.entries(Object.groupBy(orderRows,x=>x.patch)).map(([k,a])=>[k,{n:a.length,labelled:a.filter(x=>doa(x)!==null).length,doa:sum(a,x=>doa(x)??0),tests:tests(a,doa)}]))};
const v17Ids=new Set(read('v17-ids.json')),v17Orders=orderRows.filter(x=>v17Ids.has(x.signal_id));
result.claim1.v17OrderSnapshots={n:v17Orders.length,labelled:v17Orders.filter(x=>doa(x)!==null).length,doa:sum(v17Orders,x=>doa(x)??0),tests:tests(v17Orders,doa,true,true),thinned60:tests(thin(v17Orders,3600000),doa,true),actualPeak:tests(v17Orders,peak,true)};
const legacyCandidates=supplement.legacyCandidates.map(x=>({...x,facts:{spread_bps:num(x.spread_bps),book_imbalance_25bps:num(x.book_imbalance)}}));
result.claim1.legacyCandidates={n:legacyCandidates.length,labelled:legacyCandidates.filter(x=>doa(x)!==null).length,doa:sum(legacyCandidates,x=>doa(x)??0),tests:tests(legacyCandidates,doa)};
// Fixed existing bands and predeclared rank interactions; exploratory only, not selected gates.
const spreadHi=quant(expanded.map(x=>num(x.facts.spread_bps)),2/3),buyLow=quant(expanded.map(x=>num(x.facts.taker_buy_ratio_5m)),1/3);
const combos={spread10_and_seller44:f=>f.spread_bps>10&&f.taker_buy_ratio_5m<=.44,highSpreadThird_and_lowBuyThird:f=>f.spread_bps>=spreadHi&&f.taker_buy_ratio_5m<=buyLow,thinBid3_and_seller44:f=>f.bid_depth_to_order<3&&f.taker_buy_ratio_5m<=.44,sellImbalance45_and_seller44:f=>f.book_imbalance_25bps<=-.45&&f.taker_buy_ratio_5m<=.44};
result.claim1.exploratoryInteractions=Object.fromEntries(Object.entries(combos).map(([k,f])=>[k,compare(expanded.filter(x=>doa(x)!==null).map(x=>({...x,y:doa(x),g:+f(x.facts)})))]));
const positions=d.positions.filter(x=>Date.parse(x.entry_at)>=Date.parse('2026-09-19T00:00:00Z')&&x.state==='CLOSED'),fills=d.fills;
const accounting=positions.map(p=>{const ff=fills.filter(f=>f.position_id===p.id),buy=ff.filter(f=>f.side==='BUY'),sell=ff.filter(f=>f.side==='SELL'),bq=sum(buy,x=>+x.quantity),sq=sum(sell,x=>+x.quantity),bv=sum(buy,x=>+x.quote_amount),sv=sum(sell,x=>+x.quote_amount),bf=sum(buy,x=>+x.fee),sf=sum(sell,x=>+x.fee);const orderSlips=buy.map(f=>{const a=(p.attempts??[]).find(a=>a.exchange_order_id===f.exchange_order_id);return{order:f.exchange_order_id,qty:+f.quantity,ask:a?.best_ask??null,slip:a?.best_ask>0?(+f.quote_amount/+f.quantity/a.best_ask-1)*1e4:null,quoteAge:a?.quote_age_ms??null};});const complete=orderSlips.length>0&&orderSlips.every(x=>x.slip!==null);return{id:p.id,symbol:p.symbol,peak:+p.peak_price/+p.entry_price-1,patch:p.patch,signal:p.signal_id,referenceSlip:+p.reference_price>0?(+p.entry_price/+p.reference_price-1)*1e4:null,preAskSlip:p.pre?.ask>0?(+p.entry_price/p.pre.ask-1)*1e4:null,preMidSlip:p.pre?.mid>0?(+p.entry_price/p.pre.mid-1)*1e4:null,orderAskSlip:complete?sum(orderSlips,x=>x.qty*x.slip)/sum(orderSlips,x=>x.qty):null,orderSlips,attempts:p.attempts?.length??0,partial:(p.attempts??[]).some(a=>+a.executed_quantity>0&&+a.executed_quantity<+a.requested_quantity),bq,sq,positionQty:+p.original_quantity,missingFee:sum(ff,x=>x.missing_fee),entryFee:bf,exitFee:sf,gross:sv-bv,netFromFills:sv-bv-bf-sf,dbNet:num(p.realized_pnl_usdt),dbEntryFee:num(p.entry_fee_usdt),quantityMismatch:Math.abs(bq-+p.original_quantity)>1e-7||Math.abs(sq-+p.original_quantity)>1e-7,allMaker:buy.length>0&&buy.every(x=>x.all_maker===true),anyMaker:buy.some(x=>x.any_maker===true)};});
const slippage=a=>({n:a.length,reference:stats(a.map(x=>x.referenceSlip)),preAsk:stats(a.map(x=>x.preAskSlip)),preMid:stats(a.map(x=>x.preMidSlip)),orderAsk:stats(a.map(x=>x.orderAskSlip))});
result.claim2={all:slippage(accounting),DOA:slippage(accounting.filter(x=>x.peak<.003)),winners:slippage(accounting.filter(x=>x.peak>=.022)),partial:slippage(accounting.filter(x=>x.partial)),retry:slippage(accounting.filter(x=>x.attempts>1)),singleFull:slippage(accounting.filter(x=>!x.partial&&x.attempts===1)),byPatch:Object.fromEntries(Object.entries(Object.groupBy(accounting,x=>x.patch)).map(([k,a])=>[k,slippage(a)]))};
result.claim3={n:accounting.length,net:sum(accounting,x=>x.dbNet),grossFromFills:sum(accounting,x=>x.gross),entryFee:sum(accounting,x=>x.entryFee),exitFee:sum(accounting,x=>x.exitFee),netFromFills:sum(accounting,x=>x.netFromFills),quantityMismatches:accounting.filter(x=>x.quantityMismatch).length,missingFees:sum(accounting,x=>x.missingFee),maxNetDifference:Math.max(...accounting.map(x=>Math.abs(x.netFromFills-x.dbNet))),maxEntryFeeDifference:Math.max(...accounting.map(x=>Math.abs(x.entryFee-x.dbEntryFee))),allMaker:accounting.filter(x=>x.allMaker).length,anyMaker:accounting.filter(x=>x.anyMaker).length,doa:{n:accounting.filter(x=>x.peak<.003).length,net:sum(accounting.filter(x=>x.peak<.003),x=>x.dbNet),fees:sum(accounting.filter(x=>x.peak<.003),x=>x.entryFee+x.exitFee)},makerSavingsScenario:{assumedMakerBps:2,actualTakerEntryFee:sum(accounting,x=>x.entryFee),allSameFillsSavings:sum(accounting,x=>x.entryFee-x.bq*(positions.find(p=>p.id===x.id).entry_price)*.0002),notAnExpectedPnL:true}};
const ages=d.latencies.map(x=>({...x,age:num(x.execution_ref?.at)!==null&&x.api_completed_at?Date.parse(x.api_completed_at)-x.execution_ref.at:null}));
const changes=expanded.filter(x=>x.pre?.book&&x.execution_ref?.at).map(x=>({symbol:x.symbol,dt:x.pre.at-x.execution_ref.at,afterCompletion:num(x.completed_ms)!==null?x.pre.at-+x.completed_ms:null,midBps:x.execution_ref.mid>0?(x.pre.mid/x.execution_ref.mid-1)*1e4:null,spreadChange:x.pre.book.spread_bps-x.facts.spread_bps,imbalanceChange:x.pre.book.book_imbalance_25bps-x.facts.book_imbalance_25bps,askDepthPct:x.facts.ask_depth_25bps_usdt>0?(x.pre.book.ask_depth_25bps_usdt/x.facts.ask_depth_25bps_usdt-1)*100:null}));
result.claim4={latencyByTask:Object.fromEntries(Object.entries(Object.groupBy(ages,x=>x.task)).map(([k,a])=>[k,{n:a.length,api:stats(a.map(x=>num(x.latency_ms))),packetQuoteToApiCompleted:stats(a.map(x=>x.age))}])),initialToPreDispatch:{n:changes.length,elapsedMs:stats(changes.map(x=>x.dt)),afterApiCompletedMs:stats(changes.map(x=>x.afterCompletion)),midAbsBps:stats(changes.map(x=>Math.abs(x.midBps))),spreadAbsChangeBps:stats(changes.map(x=>Math.abs(x.spreadChange))),imbalanceAbsChange:stats(changes.map(x=>Math.abs(x.imbalanceChange))),askDepthAbsChangePct:stats(changes.map(x=>Math.abs(x.askDepthPct))),exactAtCompletion:changes.filter(x=>x.afterCompletion===0).length},note:'execution_ref.at is packet received/as-of time, not necessarily exchange book event timestamp; two endpoint snapshots do not recover changes during the LLM call'};
result.accountingRows=accounting;
fs.writeFileSync(new URL('results.json',import.meta.url),JSON.stringify(result,null,2)+'\n');
const minima=t=>(t??[]).filter(x=>x.p!==undefined).sort((a,b)=>a.p-b.p).slice(0,3).map(({key,p,holm,delta,n0,n1,events0,events1})=>({key,p,holm,delta,n0,n1,events0,events1}));
console.log(JSON.stringify({claim1:Object.fromEntries(Object.entries(result.claim1).map(([k,v])=>[k,v.tests?{n:v.rows??v.n,doa:v.doa??v.events,top:minima(v.tests),definitions:v.definitions&&Object.fromEntries(Object.entries(v.definitions).map(([k,v])=>[k,{events:v.events,top:minima(v.tests)}])),thin60:v.thinned60&&{n:v.thinned60.n,top:minima(v.thinned60.tests)}}:v])),claim2:result.claim2,claim3:result.claim3,claim4:result.claim4},null,2));
