alter table public.v16_momentum_shadow_candidates
  add column if not exists entry_ready boolean not null default false,
  add column if not exists entry_quality_score double precision,
  add column if not exists entry_class text;

create table if not exists public.v16_momentum_shadow_positions (
  id uuid primary key default gen_random_uuid(),
  revision text not null,
  symbol text not null,
  state text not null default 'OPEN' check (state in ('OPEN','CLOSED')),
  opened_at timestamptz not null default now(),
  entry_signal_bar_at timestamptz not null,
  entry_price double precision not null,
  entry_reference_price double precision not null,
  entry_score double precision not null,
  entry_regime text,
  entry_regime_modifier text,
  intended_notional_usdt double precision not null default 120,
  entry_expected_slippage_bps double precision not null default 0,
  entry_atr double precision,
  initial_stop_price double precision,
  peak_price double precision not null,
  trough_price double precision not null,
  current_price double precision not null,
  mfe_pct double precision not null default 0,
  mae_pct double precision not null default 0,
  remaining_fraction double precision not null default 1 check (remaining_fraction >= 0 and remaining_fraction <= 1),
  de_risk_at timestamptz,
  de_risk_price double precision,
  de_risk_fraction double precision not null default 0,
  de_risk_reason text,
  partial_net_pnl_usdt double precision not null default 0,
  exit_at timestamptz,
  exit_price double precision,
  exit_reason text,
  gross_return_pct double precision,
  net_return_pct double precision,
  net_pnl_usdt double precision,
  last_exit_score double precision not null default 0,
  last_evaluated_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create unique index if not exists v16_momentum_shadow_positions_one_open_symbol_idx
  on public.v16_momentum_shadow_positions(symbol) where state='OPEN';
create index if not exists v16_momentum_shadow_positions_state_opened_idx
  on public.v16_momentum_shadow_positions(state, opened_at desc);
create index if not exists v16_momentum_shadow_positions_closed_exit_idx
  on public.v16_momentum_shadow_positions(exit_at desc) where state='CLOSED';

create table if not exists public.v16_momentum_shadow_position_events (
  id bigint generated by default as identity primary key,
  position_id uuid not null references public.v16_momentum_shadow_positions(id) on delete cascade,
  observed_at timestamptz not null default now(),
  bar_at timestamptz not null,
  price double precision not null,
  peak_price double precision not null,
  trough_price double precision not null,
  return_pct double precision not null,
  mfe_pct double precision not null,
  mae_pct double precision not null,
  exit_score double precision not null,
  action text not null check (action in ('HOLD','DE_RISK','EXIT')),
  regime text,
  regime_modifier text,
  components jsonb not null default '{}'::jsonb,
  flow jsonb not null default '{}'::jsonb,
  book jsonb not null default '{}'::jsonb
);

create index if not exists v16_momentum_shadow_position_events_position_time_idx
  on public.v16_momentum_shadow_position_events(position_id, observed_at desc);

alter table public.v16_momentum_shadow_positions enable row level security;
alter table public.v16_momentum_shadow_position_events enable row level security;