create table if not exists public.v16_production_operator_control (
  singleton boolean primary key default true check (singleton = true),
  control_revision text not null,
  strategy_revision text not null,
  state text not null default 'READY_FOR_OPERATOR_APPROVAL' check (state in ('READY_FOR_OPERATOR_APPROVAL','OPERATOR_ACKNOWLEDGED')),
  operator_acknowledged boolean not null default false,
  acknowledged_at timestamptz,
  acknowledged_source text,
  acknowledged_note text,
  acknowledged_canary_run_id uuid references public.v16_production_canary_runs(id) on delete set null,
  acknowledged_snapshot jsonb not null default '{}'::jsonb,
  order_routing_enabled boolean not null default false check (order_routing_enabled = false),
  execution_effect text not null default 'NONE' check (execution_effect = 'NONE'),
  updated_at timestamptz not null default now()
);

create table if not exists public.v16_production_operator_control_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  action text not null,
  result text not null,
  source text,
  canary_run_id uuid references public.v16_production_canary_runs(id) on delete set null,
  snapshot jsonb not null default '{}'::jsonb
);

alter table public.v16_production_operator_control enable row level security;
alter table public.v16_production_operator_control_audit enable row level security;
revoke all on table public.v16_production_operator_control from anon, authenticated;
revoke all on table public.v16_production_operator_control_audit from anon, authenticated;

insert into public.v16_production_operator_control (
  singleton, control_revision, strategy_revision, state, operator_acknowledged,
  order_routing_enabled, execution_effect, updated_at
) values (
  true, 'V16-PRODUCTION-CONTROL-1.0.0', 'V16-PRODUCTION-CANARY-1.0.0',
  'READY_FOR_OPERATOR_APPROVAL', false, false, 'NONE', now()
)
on conflict (singleton) do update set
  control_revision = excluded.control_revision,
  strategy_revision = excluded.strategy_revision,
  order_routing_enabled = false,
  execution_effect = 'NONE',
  updated_at = now();

insert into public.edge_internal_tokens(name, token)
select 'v16-production-control', encode(gen_random_bytes(32), 'hex')
where not exists (select 1 from public.edge_internal_tokens where name='v16-production-control');
