create table if not exists public.v16_momentum_shadow_runs (
  id uuid primary key default gen_random_uuid(),
  run_at timestamptz not null default now(),
  revision text not null,
  regime text,
  regime_modifier text,
  universe_count integer not null default 0,
  stage1_count integer not null default 0,
  candidate_count integer not null default 0,
  data_error_count integer not null default 0,
  summary jsonb not null default '{}'::jsonb
);

create table if not exists public.v16_momentum_shadow_candidates (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.v16_momentum_shadow_runs(id) on delete cascade,
  observed_at timestamptz not null default now(),
  signal_bar_at timestamptz not null,
  symbol text not null,
  state text not null,
  opportunity_score double precision not null,
  micro_confirm boolean not null default false,
  regime text,
  regime_modifier text,
  metrics jsonb not null default '{}'::jsonb,
  microstructure jsonb not null default '{}'::jsonb,
  unique (run_id, symbol)
);

create index if not exists v16_momentum_shadow_candidates_symbol_observed_idx
  on public.v16_momentum_shadow_candidates(symbol, observed_at desc);
create index if not exists v16_momentum_shadow_candidates_score_idx
  on public.v16_momentum_shadow_candidates(observed_at desc, opportunity_score desc);

alter table public.v16_momentum_shadow_runs enable row level security;
alter table public.v16_momentum_shadow_candidates enable row level security;

insert into public.edge_internal_tokens(name, token)
select 'v16-momentum-shadow', encode(gen_random_bytes(32), 'hex')
where not exists (select 1 from public.edge_internal_tokens where name='v16-momentum-shadow');
